version: "3.9"
    
services:
  db:
    container_name: wordpress_db
    image: mysql:5.7
    volumes:
      - ./data/db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    
  wordpress:
    container_name: wordpress_web
    depends_on:
      - db
    image: wordpress:5.9.3-apache
    volumes:
      - ./data/wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: /run/secrets/db_password
      WORDPRESS_DB_NAME: wordpress
    secrets:
      - db_password

secrets:
  db_root_password:
    file: db_root_password.txt
  db_password:
    file: db_password.txt

volumes:
  db_data: {}
  wordpress_data: {}